### ISSUE TITLE
/start command gives error

### ISSUE THREAD

**Issue by Bergiu** [akiross/trellobot#17]
I've tried to setup the bot, but when i send /start the bot shows this error and no welcome message:

```2021-02-03 23:59:14,529 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
TypeError: start() missing 1 required positional argument: 'job_queue'
```

**Comment by Bergiu** [comment]
You need to install python-telegram-bot==12
