### ISSUE TITLE
/wlb command gives error

### ISSUE THREAD

**Issue by Bergiu** [akiross/trellobot#18]
When i try to add a board with /wlb command this error occurs:

```
2021-02-04 00:35:24,167 - root - INFO - Requested /wlb
2021-02-04 00:35:24,167 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "/app/trellobot/bot.py", line 265, in wl_board
    for ctx in security_check(bot, update):
  File "/app/trellobot/security.py", line 13, in security_check
    if update.message.chat_id == authorized_user:
AttributeError: 'CallbackContext' object has no attribute 'message'
```

**Comment by Bergiu** [comment]
You need to install python-telegram-bot==12
